### ISSUE TITLE
Files are not fully downloading (99.*% downloaded)

### ISSUE THREAD

**Issue by Dymeth** [xssnick/TON-Torrent#11]
A bug with underloading of bags is often observed. When files in bag are almost downloaded - speed drops to zero. Several files can be not loaded fully.

The problem is solved by pausing the download and restarting it again. Tested on Windows client (Win 11, x64)

Screenshots:

![image](https://github.com/xssnick/TON-Torrent/assets/21080646/0e904921-8c1e-4ea9-a019-0b1492ae97d6)

![image](https://github.com/xssnick/TON-Torrent/assets/21080646/b8369b6a-136e-4e21-a743-db2219394a87)

**Comment by xssnick** [comment]
Should be fixed in [v1.1.0](https://github.com/xssnick/TON-Torrent/releases/tag/v1.1.0)
