### ISSUE TITLE
Feature request: Add "Copy Bag ID" in bag context menu before "Export .tonbag"

### ISSUE THREAD

**Issue by Dymeth** [xssnick/TON-Torrent#13]
It would be very convenient to copy the bag's ID in when you right click on it
![image](https://github.com/xssnick/TON-Torrent/assets/21080646/96683fad-9a1b-4211-a930-c0f3b02e1ef0)

**Comment by xssnick** [comment]
Will add it, thanks for an idea.

**Comment by xssnick** [comment]
Added in [v1.1.0](https://github.com/xssnick/TON-Torrent/releases/tag/v1.1.0)
