### ISSUE TITLE
Different peers amount on different clients for same bags

### ISSUE THREAD

**Issue by Dymeth** [xssnick/TON-Torrent#14]
Looks like some peers are unavailable while loading bags. It can be test just by downloading same bag from different clients/system/locations, for example:
![image](https://github.com/xssnick/TON-Torrent/assets/21080646/9b6da3e1-ce7c-4b19-92f5-a1ed879581fa)
![image](https://github.com/xssnick/TON-Torrent/assets/21080646/a8e5a938-eb31-4305-a47c-a8758a1741ae)

**Comment by andreypfau** [comment]
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Bag ID                                                           | Description          | Downloaded | Size      | Peers | Download  | Upload    | Completed |
| 23ad8e74caf9a435f07dd8829535652c2fa0b32b7bb28d73bfe9a836e15ea1bb | ProjectTheGateway    | 436.83 MB  | 436.83 MB | 2     | 0 Bytes/s | 0 Bytes/s | true      |
| cffbea56388961470ef985fbee1f31a8b9b688ef7e0de803f5ac1355fe582ed5 | tondevstudy_second_1 | 376.11 MB  | 376.11 MB | 3     | 0 Bytes/s | 0 Bytes/s | true      |
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by xssnick** [comment]
This is kinda normal, machines with public IP intended to have more peers than machines without it. Small differences on machines with the same conditions are also not so critical, but I'll work on better discovery in the next version, thanks for the report

**Comment by xssnick** [comment]
Discovery and communication are now better in [v1.1.0](https://github.com/xssnick/TON-Torrent/releases/tag/v1.1.0)
