### ISSUE TITLE
Bag's distribution starts only after it is fully downloaded

### ISSUE THREAD

**Issue by Dymeth** [xssnick/TON-Torrent#16]
Look like server becomes a peer only after 100% of the bag data has been downloaded

**Comment by xssnick** [comment]
It should distribute every downloaded piece, not depending on progress, but yes, currently there is an issue exists with poor notification about new downloaded pieces, I will try to fix this in the next release

**Comment by xssnick** [comment]
Should be fixed in [v1.1.0](https://github.com/xssnick/TON-Torrent/releases/tag/v1.1.0)
