### ISSUE TITLE
Build error  "error TS2322: Type 'Timer' is not assignable to type 'number'"

### ISSUE THREAD

**Issue by igor9105** [xssnick/TON-Torrent#18]
Hi!
I got error during build package. Please see output from cmd below.
I have tried different version of wails 2.6.0 and 2.5.1 and got same error, I have tried because warning appears from logs and give advice change version.
```
# Building target: linux/amd64

  • Generating bindings: 
Done.
  • Installing frontend dependencies: 
Done.
  • Compiling frontend: 
    
    > frontend@0.0.0 build
    > tsc && vite build
    
    src/components/ModalAddTorrent.tsx(63,9): error TS2322: Type 'Timer' is not assignable to type 'number'.
  ERROR   exit status 2
```

**Comment by igor9105** [comment]
I have :
Node.js --version  v21.2.0  
typescript@5.3.2 
tsc --version 10.2.4
 I have tried update typescript version but got message that I already use latest version

**Comment by xssnick** [comment]
I've changed code a bit, could you please pull from master and try again?
